# Generated by Django 4.1.7 on 2023-03-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_alter_producto_sku'),
        ('usuarios', '0002_profile_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='products',
            field=models.ManyToManyField(to='productos.producto'),
        ),
    ]
