# Generated by Django 4.1.7 on 2023-03-02 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_profile_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
