# Generated by Django 4.1.7 on 2023-02-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('brand', models.CharField(max_length=30, null=True)),
                ('price', models.FloatField()),
            ],
        ),
    ]
