# Generated by Django 4.1.7 on 2023-02-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(default='45205574', max_length=8, unique=True),
        ),
    ]
