# Generated by Django 4.1.7 on 2023-02-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.IntegerField(default=97234174, primary_key=True, serialize=False),
        ),
    ]
