# Generated by Django 4.1.7 on 2023-02-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_remove_producto_id_alter_producto_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.IntegerField(default=55764353, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('brand', models.CharField(max_length=30, null=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
