# Generated by Django 4.1.7 on 2023-02-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_product_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('sku', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('brand', models.CharField(max_length=30, null=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
