# Generated by Django 4.1.7 on 2023-02-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_producto_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.IntegerField(default=40424175, primary_key=True, serialize=False),
        ),
    ]
