# Generated by Django 4.1.7 on 2023-03-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_producto_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.IntegerField(default=64753066, primary_key=True, serialize=False),
        ),
    ]
