# Generated by Django 4.1.7 on 2023-03-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_alter_producto_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.IntegerField(default=86603065, primary_key=True, serialize=False),
        ),
    ]
