# Generated by Django 4.1.7 on 2023-03-03 19:16

from django.db import migrations, models
import productos.utils


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_alter_producto_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.AutoField(default=productos.utils.random_number, primary_key=True, serialize=False),
        ),
    ]
